"""empty message

Revision ID: 2a6cd773ac83
Revises: None
Create Date: 2016-11-26 23:34:34.029175

"""

# revision identifiers, used by Alembic.
revision = '2a6cd773ac83'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.Column('disciplina', sa.String(length=255), nullable=True),
    sa.Column('poza', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('hashtag')
    ### end Alembic commands ###
