"""empty message

Revision ID: 34478ad2482d
Revises: 2a6cd773ac83
Create Date: 2016-12-11 23:11:19.826905

"""

# revision identifiers, used by Alembic.
revision = '34478ad2482d'
down_revision = '2a6cd773ac83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidential')
    ### end Alembic commands ###
