"""empty message

Revision ID: 374396d609c0
Revises: 34478ad2482d
Create Date: 2016-12-11 23:12:07.473372

"""

# revision identifiers, used by Alembic.
revision = '374396d609c0'
down_revision = '34478ad2482d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confidential', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confidential', 'password')
    ### end Alembic commands ###
